// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ro'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	routes: {
		/**
		 * /​e​n​/​{​0​}
		 * @param {unknown} 0
		 */
		href: RequiredParams<'0'>
		auth: {
			/**
			 * /​e​n​/​l​o​g​i​n
			 */
			logIn: string
			/**
			 * /​e​n​/​s​i​g​n​-​u​p
			 */
			signUp: string
			/**
			 * /​e​n​/​l​o​g​o​u​t
			 */
			logOut: string
		}
		user: {
			/**
			 * /​e​n​/
			 */
			homepage: string
		}
	}
	/**
	 * H​e​l​l​o
	 */
	hi: string
	auth: {
		/**
		 * c​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​l​o​g​i​n
		 */
		login: string
		/**
		 * l​o​g​o​u​t
		 */
		logout: string
	}
}

export type TranslationFunctions = {
	routes: {
		/**
		 * /en/{0}
		 */
		href: (arg0: unknown) => LocalizedString
		auth: {
			/**
			 * /en/login
			 */
			logIn: () => LocalizedString
			/**
			 * /en/sign-up
			 */
			signUp: () => LocalizedString
			/**
			 * /en/logout
			 */
			logOut: () => LocalizedString
		}
		user: {
			/**
			 * /en/
			 */
			homepage: () => LocalizedString
		}
	}
	/**
	 * Hello
	 */
	hi: () => LocalizedString
	auth: {
		/**
		 * click here to login
		 */
		login: () => LocalizedString
		/**
		 * logout
		 */
		logout: () => LocalizedString
	}
}

export type Formatters = {}
