// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ro'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o
	 */
	hi: string
	auth: {
		/**
		 * c​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​l​o​g​i​n
		 */
		login: string
		/**
		 * l​o​g​o​u​t
		 */
		logout: string
	}
}

export type TranslationFunctions = {
	/**
	 * Hello
	 */
	hi: () => LocalizedString
	auth: {
		/**
		 * click here to login
		 */
		login: () => LocalizedString
		/**
		 * logout
		 */
		logout: () => LocalizedString
	}
}

export type Formatters = {}
