// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ro'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	routes: {
		/**
		 * /​e​n​/​{​0​}
		 * @param {unknown} 0
		 */
		href: RequiredParams<'0'>
		auth: {
			/**
			 * /​e​n​/​l​o​g​i​n
			 */
			login: string
			/**
			 * /​e​n​/​s​i​g​n​-​u​p
			 */
			signUp: string
			/**
			 * /​e​n​/​l​o​g​o​u​t
			 */
			logout: string
		}
		user: {
			/**
			 * /​e​n​/​u​s​e​r
			 */
			homepage: string
		}
		sprints: {
			/**
			 * /​e​n​/​s​p​r​i​n​t​s
			 */
			index: string
			/**
			 * /​e​n​/​s​p​r​i​n​t​s​/​{​0​}
			 * @param {unknown} 0
			 */
			details: RequiredParams<'0'>
		}
	}
	pages: {
		auth: {
			login: {
				/**
				 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
				 */
				title: string
				/**
				 * E​m​a​i​l​ ​a​d​d​r​e​s​s
				 */
				email: string
				/**
				 * P​a​s​s​w​o​r​d
				 */
				password: string
				/**
				 * S​i​g​n​ ​I​n
				 */
				submit: string
				/**
				 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
				 */
				noAccount: string
				/**
				 * S​i​g​n​ ​u​p
				 */
				signUp: string
			}
			signUp: {
				/**
				 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
				 */
				title: string
				/**
				 * F​u​l​l​ ​N​a​m​e
				 */
				name: string
				/**
				 * E​m​a​i​l​ ​a​d​d​r​e​s​s
				 */
				email: string
				/**
				 * P​a​s​s​w​o​r​d
				 */
				password: string
				/**
				 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
				 */
				confirmPassword: string
				/**
				 * S​i​g​n​ ​U​p
				 */
				submit: string
				/**
				 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
				 */
				haveAccount: string
				/**
				 * S​i​g​n​ ​i​n
				 */
				signIn: string
			}
			/**
			 * l​o​g​o​u​t
			 */
			logout: string
		}
	}
	errors: {
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d
		 */
		INVALID_CREDENTIALS: string
		/**
		 * A​n​ ​i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
		 */
		INTERNAL_SERVER_ERROR: string
		/**
		 * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​r​e​s​o​u​r​c​e​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
		 */
		NOT_FOUND: string
		/**
		 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​d​ ​t​o​ ​p​e​r​f​o​r​m​ ​t​h​i​s​ ​a​c​t​i​o​n
		 */
		UN_AUTHORIZED: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​a​l​l​o​w​e​d
		 */
		ACTION_NOT_ALLOWED: string
		/**
		 * B​a​d​ ​r​e​q​u​e​s​t​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​p​u​t
		 */
		BAD_REQUEST: string
		/**
		 * {​f​i​e​l​d​}​ ​i​s​ ​r​e​q​u​i​r​e​d
		 * @param {unknown} field
		 */
		required: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
		 * @param {unknown} field
		 * @param {unknown} min
		 */
		min_length: RequiredParams<'field' | 'min'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
		 * @param {unknown} field
		 * @param {unknown} max
		 */
		max_length: RequiredParams<'field' | 'max'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 * @param {unknown} field
		 */
		one_uppercase: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 * @param {unknown} field
		 */
		one_lowercase: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r
		 * @param {unknown} field
		 */
		one_number: RequiredParams<'field'>
		/**
		 * {​f​i​e​l​d​}​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
		 * @param {unknown} field
		 */
		one_special: RequiredParams<'field'>
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
		 */
		password_mismatch: string
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
		 */
		invalid_email: string
	}
	blocks: {
		header: {
			/**
			 * S​p​r​i​n​t​s
			 */
			sprints: string
		}
	}
	fields: {
		name: {
			/**
			 * N​a​m​e
			 */
			label: string
			/**
			 * A​h​m​a​d​ ​A​l​d​a​l​i
			 */
			placeholder: string
		}
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * d​e​v​@​a​h​m​a​d​.​m​e
			 */
			placeholder: string
		}
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * •​•​•​•​•​•​•​•
			 */
			placeholder: string
		}
		confirmPassword: {
			/**
			 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * •​•​•​•​•​•​•​•
			 */
			placeholder: string
		}
	}
}

export type TranslationFunctions = {
	routes: {
		/**
		 * /en/{0}
		 */
		href: (arg0: unknown) => LocalizedString
		auth: {
			/**
			 * /en/login
			 */
			login: () => LocalizedString
			/**
			 * /en/sign-up
			 */
			signUp: () => LocalizedString
			/**
			 * /en/logout
			 */
			logout: () => LocalizedString
		}
		user: {
			/**
			 * /en/user
			 */
			homepage: () => LocalizedString
		}
		sprints: {
			/**
			 * /en/sprints
			 */
			index: () => LocalizedString
			/**
			 * /en/sprints/{0}
			 */
			details: (arg0: unknown) => LocalizedString
		}
	}
	pages: {
		auth: {
			login: {
				/**
				 * Sign in to your account
				 */
				title: () => LocalizedString
				/**
				 * Email address
				 */
				email: () => LocalizedString
				/**
				 * Password
				 */
				password: () => LocalizedString
				/**
				 * Sign In
				 */
				submit: () => LocalizedString
				/**
				 * Don't have an account?
				 */
				noAccount: () => LocalizedString
				/**
				 * Sign up
				 */
				signUp: () => LocalizedString
			}
			signUp: {
				/**
				 * Create your account
				 */
				title: () => LocalizedString
				/**
				 * Full Name
				 */
				name: () => LocalizedString
				/**
				 * Email address
				 */
				email: () => LocalizedString
				/**
				 * Password
				 */
				password: () => LocalizedString
				/**
				 * Confirm Password
				 */
				confirmPassword: () => LocalizedString
				/**
				 * Sign Up
				 */
				submit: () => LocalizedString
				/**
				 * Already have an account?
				 */
				haveAccount: () => LocalizedString
				/**
				 * Sign in
				 */
				signIn: () => LocalizedString
			}
			/**
			 * logout
			 */
			logout: () => LocalizedString
		}
	}
	errors: {
		/**
		 * Invalid email or password
		 */
		INVALID_CREDENTIALS: () => LocalizedString
		/**
		 * An internal server error occurred. Please try again later
		 */
		INTERNAL_SERVER_ERROR: () => LocalizedString
		/**
		 * The requested resource was not found
		 */
		NOT_FOUND: () => LocalizedString
		/**
		 * You are not authorized to perform this action
		 */
		UN_AUTHORIZED: () => LocalizedString
		/**
		 * This action is not allowed
		 */
		ACTION_NOT_ALLOWED: () => LocalizedString
		/**
		 * Bad request. Please check your input
		 */
		BAD_REQUEST: () => LocalizedString
		/**
		 * {field} is required
		 */
		required: (arg: { field: unknown }) => LocalizedString
		/**
		 * {field} must be at least {min} characters long
		 */
		min_length: (arg: { field: unknown, min: unknown }) => LocalizedString
		/**
		 * {field} must be at most {max} characters long
		 */
		max_length: (arg: { field: unknown, max: unknown }) => LocalizedString
		/**
		 * {field} must contain at least one uppercase letter
		 */
		one_uppercase: (arg: { field: unknown }) => LocalizedString
		/**
		 * {field} must contain at least one lowercase letter
		 */
		one_lowercase: (arg: { field: unknown }) => LocalizedString
		/**
		 * {field} must contain at least one number
		 */
		one_number: (arg: { field: unknown }) => LocalizedString
		/**
		 * {field} must contain at least one special character
		 */
		one_special: (arg: { field: unknown }) => LocalizedString
		/**
		 * Passwords do not match
		 */
		password_mismatch: () => LocalizedString
		/**
		 * Invalid email address
		 */
		invalid_email: () => LocalizedString
	}
	blocks: {
		header: {
			/**
			 * Sprints
			 */
			sprints: () => LocalizedString
		}
	}
	fields: {
		name: {
			/**
			 * Name
			 */
			label: () => LocalizedString
			/**
			 * Ahmad Aldali
			 */
			placeholder: () => LocalizedString
		}
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * dev@ahmad.me
			 */
			placeholder: () => LocalizedString
		}
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * ••••••••
			 */
			placeholder: () => LocalizedString
		}
		confirmPassword: {
			/**
			 * Confirm Password
			 */
			label: () => LocalizedString
			/**
			 * ••••••••
			 */
			placeholder: () => LocalizedString
		}
	}
}

export type Formatters = {}
